services:
  - type: web
    name: my-mood-log
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-mood-log-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: my-mood-log-db
    plan: free