default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_mood_log

test:
  <<: *default
  database: my_mood_log_test

production:
  <<: *default
  # Renderでは、この1行（url）の設定だけでデータベースに繋がります
  url: <%= ENV['DATABASE_URL'] %>